### ISSUE TITLE
A lot of "ignores"

### ISSUE THREAD

**Issue by jbrucker** [Sahanon-P/ku-polls#25]
https://github.com/Sahanon-P/ku-polls/blob/77854f5f6f0ef92b7ef188264c4cbe358f8b0643/setup.cfg#L10-L15

It is better to modify your code to conform to the recommended style
instead of ignoring the style guides.
Are all these ignores really necessary?
I'm going to test student code without *any* ignores.

**Comment by Sahanon-P** [comment]
I've delete all unnecessary ignore but in the exclude I need to put both __init__ in mysite and polls because it not contain any code but the flake8 still has a problem to fix with that so I need to put both of them in exclude.
